import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { Logger } from "@bilibili-notify/internal";
import { KeyManager } from "./key-manager";
import { deriveKeyFromPassphrase } from "./secret-box";

/**
 * Resolves the 32-byte AES key used to encrypt at-rest secrets.
 *
 * Two strategies:
 *   - {@link PassphraseKeyProvider} — key scrypt-derived from an injected
 *     passphrase (`bootstrap.cookieEncryptionKey` / `BN_COOKIE_KEY`). The key
 *     itself is NEVER written to disk; only a non-secret per-install salt is.
 *     This is the only mode that gives real at-rest protection.
 *   - {@link FileKeyProvider} — legacy behaviour: a random key file living
 *     next to the ciphertext (auto-generated by {@link KeyManager}). Key and
 *     data co-located → obfuscation, not protection. Kept as the zero-config
 *     fallback (and the only path the koishi shell ever uses).
 */
export interface KeyProvider {
	getKey(): Promise<Buffer>;
	/** Whether the key can be rotated in place. Injected passphrases cannot. */
	readonly resettable: boolean;
	/** Rotate the key (file mode) or, for passphrase mode, just return it unchanged. */
	resetKey(): Promise<Buffer>;
	/** `true` = injected passphrase (real encryption); `false` = co-located key file. */
	readonly protected: boolean;
}

export class FileKeyProvider implements KeyProvider {
	readonly resettable = true;
	readonly protected = false;
	private readonly km: KeyManager;
	constructor(keyPath: string, logger: Logger) {
		this.km = new KeyManager(keyPath, logger);
	}
	getKey(): Promise<Buffer> {
		return this.km.loadOrCreate();
	}
	resetKey(): Promise<Buffer> {
		return this.km.createNew();
	}
}

export class PassphraseKeyProvider implements KeyProvider {
	readonly resettable = false;
	readonly protected = true;
	private cached: Buffer | null = null;
	constructor(
		private readonly passphrase: string,
		private readonly saltPath: string,
		private readonly logger: Logger,
	) {}

	async getKey(): Promise<Buffer> {
		if (this.cached) return this.cached;
		const salt = await this.loadOrCreateSalt();
		this.cached = deriveKeyFromPassphrase(this.passphrase, salt);
		this.logger.debug("[key] 使用注入密钥派生 AES-256 密钥 (scrypt)");
		return this.cached;
	}

	/** Injected key cannot be rotated — return it unchanged (caller still wipes the ciphertext). */
	resetKey(): Promise<Buffer> {
		return this.getKey();
	}

	private async loadOrCreateSalt(): Promise<Buffer> {
		try {
			const hex = (await readFile(this.saltPath, "utf8")).trim();
			if (/^[0-9a-f]{32,}$/i.test(hex)) return Buffer.from(hex, "hex");
		} catch {
			// fall through to create
		}
		const salt = randomBytes(16);
		await mkdir(dirname(this.saltPath), { recursive: true });
		const tmp = `${this.saltPath}.tmp`;
		await writeFile(tmp, salt.toString("hex"), "utf8");
		try {
			await rename(tmp, this.saltPath);
		} catch (e) {
			await unlink(tmp).catch(() => {});
			throw e;
		}
		return salt;
	}
}

export interface CreateKeyProviderOptions {
	/** Injected passphrase. When present → PassphraseKeyProvider; else FileKeyProvider. */
	passphrase?: string;
	/** Legacy random-key file path (FileKeyProvider). */
	keyPath: string;
	/** Per-install scrypt salt path (PassphraseKeyProvider). */
	saltPath: string;
	logger: Logger;
}

export function createKeyProvider(opts: CreateKeyProviderOptions): KeyProvider {
	const pass = opts.passphrase?.trim();
	if (pass) return new PassphraseKeyProvider(pass, opts.saltPath, opts.logger);
	return new FileKeyProvider(opts.keyPath, opts.logger);
}
