/**
 * 假头像:四张 64×64 纯色 png,各一百来字节。
 *
 * 必须是**真的 png**:建订阅时宿主先按 data URL 声明的类型核魔数(`89 50 4E 47 …`),对不上
 * 整条订阅建不成。只收位图、不收 SVG(ADR-0019 决策 49)。一次性生成好贴在这里 —— 拓展包旁边
 * 没有 node_modules,也没必要为几张色块在运行时现编码。
 */
export const FAKE_AVATARS: readonly string[] = [
	// teal #14b8a6
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAUElEQVR42u3PQQkAAAgEsAth/6cZjGcE38JgBZaafi0CAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICApcFwfUhWhBJI9UAAAAASUVORK5CYII=",
	// amber #f59e0b
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAT0lEQVR42u3PMQ0AAAgDsP34f3HJjwRukiY10EzXaxEQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQuCxmweF4NID8QAAAAABJRU5ErkJggg==",
	// rose #f43f5e
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAAUElEQVR42u3PQQkAAAgEsGtmE/sHMIARfAuDFVim+rUICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICFwWAGEReKYdWCsAAAAASUVORK5CYII=",
	// indigo #6366f1
	"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAATklEQVR42u3PQQkAAAgEsOsq2N8GRvAtDFZgqZ7XIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBwWV7OoZaC+o1lAAAAAElFTkSuQmCC",
];
