// AI 服务商注册表。本体在零依赖的 constants(设置页经 /constants 子路径消费),
// 这里给后端消费者补一条根入口的路 —— 与 FEATURE_KEYS 同样的两路一值。
export {
	type ActivePersonaShape,
	AI_PROVIDER_IDS,
	AI_PROVIDERS,
	type AIPersonaShape,
	type AIPresetShape,
	type AIProviderId,
	type AIProviderMeta,
	type AIProviderProfileShape,
	API_FLAVOR_IDS,
	type APIFlavorId,
	addressNounFor,
	BRIDGE_DISPATCH_KEY,
	BRIDGE_EXTENSION_ID,
	BUILTIN_AI_PRESETS,
	CONNECTION_PLATFORMS,
	type ConnectionPlatform,
	colorFromUid,
	connectionDispatchKey,
	countsAsDelivery,
	countsAsFailure,
	DEFAULT_ROAST_SCHEDULE,
	EMPTY_AI_PROVIDER_PROFILE,
	INBOUND_CAPABLE_PLATFORMS,
	inboundGapReason,
	isDirectConnection,
	isExtensionConnection,
	isMirrorPrefix,
	isTargetPaused,
	isWebhookConnection,
	isWebhookPlatform,
	LINK_LIMITS,
	LINK_REPLY_FORMS,
	type LinkLimits,
	type LinkReplyForm,
	MIRROR_PREFIX_RE,
	PLATFORM_REGISTRY,
	type PlatformDescriptor,
	PUSH_STATUSES,
	platformCanReceiveReply,
	platformDescriptor,
	platformSupportsAtAll,
	providerMeta,
	resolveActivePersona,
	resolveAIProfile,
	resolveChatThinkingLevel,
	THINKING_LEVELS,
	type ThinkingLevel,
	UP_COLORS,
	WEB_SEARCH_BACKEND_IDS,
	WEB_SEARCH_BACKENDS,
	WEBHOOK_PLATFORMS,
	type WebhookPlatform,
	type WebSearchBackendId,
	type WebSearchBackendMeta,
	webSearchBackendMeta,
} from "./constants";
export * from "./platform";
/**
 * 推送源契约 —— 核心的三个 adapter 与拓展的桥都实现它。见 `push-source.ts` 的文件头。
 */
export {
	type Connector,
	type InboundGroupMessage,
	type InboundMeta,
	type InboundPrivateMessage,
	type InboundSinks,
	inboundIdentity,
	type PlatformAdapter,
	type PlatformDialect,
	type ProbeResult,
} from "./push-source";
export * from "./schema";
export * from "./util";
